# Generated by Django 3.2.21 on 2023-10-04 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
